#!/usr/bin/env python3
"""Emit a Markdown table of every Sibyl Memory read and write in the repo,
with file and line, so a judge can find them in under two minutes.

    .venv/bin/python scripts/memory_index.py > docs/MEMORY_INDEX.md
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STORE = ROOT / "memory-service" / "grudge_memory" / "store.py"

CALLS = {
    "set_entity": ("WARM", "write"), "get_entity": ("WARM", "read"), "list_entities": ("WARM", "read"),
    "write_event": ("COLD", "write"), "read_events": ("COLD", "read"),
    "set_state": ("HOT", "write"), "get_state": ("HOT", "read"),
    "set_reference": ("REFERENCE", "write"), "get_reference": ("REFERENCE", "read"),
    "search_entities": ("SEARCH entity tier", "read"), ".search(": ("SEARCH cross-tier", "read"),
    "multi_record_search(": ("SEARCH multi-record", "read"),
}


def main() -> None:
    lines = STORE.read_text().splitlines()
    func = None
    rows = []
    for i, line in enumerate(lines, 1):
        m = re.match(r"\s*def (\w+)\(", line)
        if m:
            func = m.group(1)
        for needle, (tier, kind) in CALLS.items():
            key = needle if needle.endswith("(") else f".{needle}("
            if key in line and "def " not in line:
                rows.append((i, func, tier, kind, line.strip()[:90]))
    rel = STORE.relative_to(ROOT)
    print("# Every memory read and write in GRUDGE\n")
    print(f"All Sibyl Memory access lives in one file: `{rel}`. Generated by `scripts/memory_index.py`.\n")
    print("| line | function | tier | op | call |")
    print("|-----:|----------|------|----|------|")
    for i, f, tier, kind, code in rows:
        print(f"| [{i}]({rel}#L{i}) | `{f}` | {tier} | {kind} | `{code.replace('|', '\\|')}` |")
    print(f"\n{len(rows)} call sites. Brokers reach them only through HTTP (`broker/src/memory.js`).")
    # Broker side: the HTTP client methods
    mem = (ROOT / "broker" / "src" / "memory.js").read_text().splitlines()
    print("\n## Broker side (HTTP client, no local fallback)\n")
    print("| line | method | route |")
    print("|-----:|--------|-------|")
    for i, line in enumerate(mem, 1):
        m = re.match(r"\s*(\w+)\([^)]*\)\s*\{\s*return this\.call\(\"(\w+)\", `?([^`\"]+)", line)
        if m:
            print(f"| [{i}](broker/src/memory.js#L{i}) | `{m.group(1)}` | {m.group(2)} `{m.group(3)}` |")


if __name__ == "__main__":
    main()
